linters-settings:
  govet:
    check-shadowing: true
    enable:  
       - fieldalignment
  revive:
    min-confidence: 0
  gocyclo:
    min-complexity: 64
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  # TODO: Revisit after the refactor
  funlen:
    lines: 220
    statements: 120

linters:
  enable-all: true
  disable:
    - depguard
    - thelper
    - ireturn
    - maintidx
    - wrapcheck
    - gosec
    - gocritic
    - errorlint
    - gci
    - gofumpt
    - nlreturn
    - noctx
    - paralleltest
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - tagliatelle
    - maligned
    - unparam
    - lll
    - gochecknoinits
    - gochecknoglobals
    - dupl
    - wsl
    - godox
    - gomnd
    # TODO: Revisit after the refactor
    - gocognit
    - testpackage
    - goerr113
    - godot
    - nestif
